"""Unit tests for the PDF loader (pdf_loader.py)."""

from __future__ import annotations

import pathlib

import pytest

from app.ingestion.pdf_loader import IngestionResult, load_pdf
from app.models.document import DocumentMetadata, DocumentPage

# Path to the synthetic fixture PDF generated by scripts/create_sample_pdf.py
FIXTURE_PDF = pathlib.Path(__file__).parents[2] / "data" / "samples" / "deal_002.pdf"


# ── IngestionResult ────────────────────────────────────────────────────────────

class TestIngestionResult:
    def test_success_property_true_when_metadata_set(self):
        meta = DocumentMetadata(
            document_id="DEAL-002",
            filename="deal_002.pdf",
            source_path="/data/deal_002.pdf",
            page_count=3,
            file_size_bytes=12000,
        )
        result = IngestionResult(metadata=meta, pages=[])
        assert result.success is True

    def test_success_property_false_when_error_set(self):
        result = IngestionResult(error="File not found")
        assert result.success is False

    def test_default_pages_is_empty_list(self):
        result = IngestionResult(error="something")
        assert result.pages == []


# ── load_pdf: valid file ───────────────────────────────────────────────────────

@pytest.mark.skipif(
    not FIXTURE_PDF.exists(),
    reason="deal_002.pdf fixture not found; run scripts/create_sample_pdf.py",
)
class TestLoadPdfValid:
    def test_load_returns_success(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.success is True
        assert result.error is None

    def test_metadata_document_id(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.metadata.document_id == "DEAL-002"

    def test_metadata_filename(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.metadata.filename == "deal_002.pdf"

    def test_metadata_file_type(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.metadata.file_type == "pdf"

    def test_metadata_page_count(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.metadata.page_count == 3

    def test_metadata_file_size_positive(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert result.metadata.file_size_bytes > 0

    def test_pages_count_matches_page_count(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        assert len(result.pages) == result.metadata.page_count

    def test_pages_are_one_indexed(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        page_numbers = [p.page_number for p in result.pages]
        assert page_numbers == [1, 2, 3]

    def test_pages_in_deterministic_order(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        numbers = [p.page_number for p in result.pages]
        assert numbers == sorted(numbers)

    def test_pages_have_extractable_text(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        # All pages in the synthetic fixture should have text.
        for page in result.pages:
            assert page.has_extractable_text is True

    def test_page_1_contains_expected_text(self):
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        page1 = result.pages[0]
        assert "DEAL-002" in page1.raw_text or "COMMERCIAL LOAN" in page1.raw_text

    def test_financial_text_preserved(self):
        """Percentages, amounts, and qualifiers must not be stripped."""
        result = load_pdf(FIXTURE_PDF, "DEAL-002")
        all_text = " ".join(p.raw_text for p in result.pages)
        assert "8.5%" in all_text
        assert "50,000,000" in all_text
        assert "1.25" in all_text  # DSCR covenant
        assert "subject to" in all_text.lower()
        assert "not less than" in all_text.lower()

    def test_string_path_accepted(self):
        """load_pdf should accept str as well as Path."""
        result = load_pdf(str(FIXTURE_PDF), "DEAL-002")
        assert result.success is True


# ── load_pdf: error cases ──────────────────────────────────────────────────────

class TestLoadPdfErrors:
    def test_missing_file_returns_error(self, tmp_path):
        missing = tmp_path / "nonexistent.pdf"
        result = load_pdf(missing, "DEAL-X")
        assert result.success is False
        assert result.error is not None
        assert "not found" in result.error.lower() or "no such" in result.error.lower() or "not found" in result.error.lower()
        assert result.metadata is None
        assert result.pages == []

    def test_corrupt_pdf_returns_error(self, tmp_path):
        bad_pdf = tmp_path / "corrupt.pdf"
        bad_pdf.write_bytes(b"This is not a valid PDF file at all.")
        result = load_pdf(bad_pdf, "DEAL-X")
        assert result.success is False
        assert result.error is not None
        assert result.metadata is None

    def test_directory_path_returns_error(self, tmp_path):
        result = load_pdf(tmp_path, "DEAL-X")
        assert result.success is False
        assert result.error is not None

    def test_empty_bytes_pdf_returns_error(self, tmp_path):
        empty = tmp_path / "empty.pdf"
        empty.write_bytes(b"")
        result = load_pdf(empty, "DEAL-X")
        assert result.success is False
